apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: bf-jenkins/guia-jenkins:${IMAGE_TAG}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

